### ISSUE TITLE
add ubus calls

### ISSUE THREAD

**Issue by aparcar** [sargon/ddhcpd#3]
As you offer a CLI changing parameters on the run, it should be easy to add some UBUS functionality. 

Is that a planned feature?

**Comment by sargon** [comment]
That sounds like you can plug that into an extra binary, maybe an extension to ddhcpdctl or directly into the hook binary. My goal with ddhcpd is to keep all deployment related stuff out of the main codebase.
Otherwise I would have extra code for every mesh protocoll or whatever in there, too. But there is no limitation to extend those in the environment.

**Comment by christf** [comment]
I like the approach using hooks. It keeps the complexity away of ddhcpd.
